# 应用服务 WEB 访问端口
server:
  port: 8080

# spring配置
spring:
  application:
    name: blog
  mvc:
    static-path-pattern: /static/**


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动
    name: defaultDataSource   # 数据源名称
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 2468520
  # Thymeleaf (ThymeleafAutoConfiguration)
  thymeleaf:
    cache: false  # 开启模板缓存（默认值： true ）
    check-template-location: true  # 检查模板位置是否正确（默认值 :true ）
    enabled: true          #开启 MVC Thymeleaf 视图解析（默认值： true ）
    encoding: UTF-8        #模板编码
    excluded-view-names:   # 要被排除在解析之外的视图名称列表，⽤逗号分隔
    mode: HTML5            # 要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
    prefix: classpath:/templates/   # 在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
    suffix: .html                   # 在构建URL时添加到视图名称后的后缀（默认值：.html）
    # thymeleaf会解析templates中所有的页面


# MyBatis映射配置
mybatis:
  mapper-locations: classpath:mappers/*.xml  #指定Mybatis的Mapper文件位置
  type-aliases-package: com.ht.blog.pojo  #指定Mybatis的实体目录
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名规范

# pageHelper 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true   # 页参数合理化
  support-methods-arguments: true    # 启用了分页,并且先执行了count后面的查询也拼接了limit

# 指定日志级别
logging:
  level:
    root: info
    com.ht: debug
  file:
    path: log/blog.log